"""Snakemake workflow for training and evaluating tokenizers."""
from pathlib import Path

# Parameters
n_jets = [10_000_000]
# tokenizers = ["kmeans"]  # TODO: unclear how to integrate this one, useful as a baseline!
tokenizers = ["vqvae", "transformer_vqvae", "set2vec_vqvae", "diffusion_vqvae"]
output_dir = Path("/sdf/group/mli/samklein/code/gold_diggers/results/long_run")
# TODO: set trainer.max_epochs=30 properly

rule all:
    input:
        expand(output_dir / "{tokenizer}/n_jets_{num_jets}/SUCCESS.txt", tokenizer=tokenizers, num_jets=n_jets),
        expand(output_dir / "classifier/feature_cf_{num_jets}/SUCCESS.txt", num_jets=n_jets),
        expand(output_dir / "classifier/{tokenizer}_cf_{num_jets}/SUCCESS.txt", tokenizer=tokenizers, num_jets=n_jets),

rule train_tokenizer:
    output:
        output_dir / "{tokenizer}/n_jets_{num_jets}/SUCCESS.txt",
        ckpt = output_dir / "{tokenizer}/n_jets_{num_jets}/checkpoints/last.ckpt",
    params:
        output_dir = output_dir,
        clip_grad = lambda wildcards: "trainer.gradient_clip_val=1.0" if wildcards.tokenizer != "kmeans" else "",
        callbacks = lambda wildcards: "callbacks=encode" if wildcards.tokenizer != "kmeans" else "",
    wildcard_constraints:
        tokenizer = "|".join(tokenizers),
    group:
        "train_tokenizers",
    shell:
        """
        pixi run python scripts/train.py \
            output_dir={params.output_dir} \
            project_name={wildcards.tokenizer} \
            network_name=n_jets_{wildcards.num_jets} \
            datamodule.num_jets={wildcards.num_jets} \
            model={wildcards.tokenizer} \
            trainer.max_epochs=30 \
            +trainer.num_sanity_val_steps=0 \
            {params.clip_grad} \
            {params.callbacks}
        """

rule train_token_classifier:
    input:
        tokenizer_ckpt = output_dir / "{tokenizer}/n_jets_{num_jets}/checkpoints/last.ckpt"
    output:
        output_dir / "classifier/{tokenizer}_cf_{num_jets}/SUCCESS.txt"
    params:
        output_dir = output_dir,
    group:
        "train_tokenizers",
    shell:
        """
        pixi run python scripts/train.py \
            output_dir={params.output_dir} \
            project_name=classifier \
            network_name={wildcards.tokenizer}_cf_{wildcards.num_jets} \
            datamodule=atlas_mappable \
            datamodule.num_jets={wildcards.num_jets} \
            model=token_classifier \
            model.tokenizer_ckpt={input.tokenizer_ckpt} \
            trainer.max_epochs=30 \
            +trainer.num_sanity_val_steps=0
        """

rule train_feature_classifier:
    output:
        output_dir / "classifier/feature_cf_{num_jets}/SUCCESS.txt"
    params:
        output_dir = output_dir,
    shell:
        """
        pixi run python scripts/train.py \
            output_dir={params.output_dir} \
            project_name=classifier \
            network_name=feature_cf_{wildcards.num_jets} \
            datamodule=atlas_mappable \
            datamodule.num_jets={wildcards.num_jets} \
            model=feature_classifier \
            trainer.max_epochs=30 \
            callbacks=classify \
        """