"""Snakemake workflow for training and evaluating tokenizers."""
from pathlib import Path

# Parameters
n_jets = [10_000]
output_dir = Path("/sdf/group/mli/samklein/code/gold_diggers/results")

rule all:
    input:
        expand(output_dir / f"{model}/{num_jets}/SUCCESS.txt", model=["kmeans"], num_jets=n_jets)

rule train_kmeans_tokenizer:
    output:
        output_dir / "{model}/{num_jets}/SUCCESS.txt"
    params:
        output_dir = output_dir,
        clip_grad = "trainer.gradient_clip_val=1.0" if wildcards.model != "kmeans" else 0.0,
    shell:
        """
        pixi run python scripts/train.py \
            output_dir={params.output_dir} \
            project_name={wildcards.model} \
            exp_name={wildcards.num_jets} \
            datamodule.num_jets={params.num_jets} \
            model={wildcards.model} \
            trainer.num_sanity_val_steps=0 \
            {params.clip_grad} \
        """