---
executor: slurm
jobs: 100
printshellcmds: true
use-singularity: false
restart-times: 0
rerun-incomplete: true
rerun-triggers: mtime
default-resources:
  - slurm_account=mli:bax@turing
  - slurm_partition=turing
  - runtime=540
  - mem_mb=32000
  - cpus_per_gpu=4
  - gres=gpu:1
