---
# configs/model/hybrid_vqvae.yaml
# MLP encoder + Transformer decoder
_target_: heptokens.models.vq_vae.LitVqVae
encoder:
  _target_: heptokens.models.coders.Encoder
  _partial_: true
  model:
    _target_: heptokens.models.coders.CoderModel
    _partial_: true
    hidden_dims: [128, 256, 512]
decoder:
  _target_: heptokens.models.coders.Decoder
  _partial_: true
  model:
    _target_: heptokens.models.transformer.Transformer
    _partial_: true
    d_model: 128
    n_heads: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.
    activation: gelu
codebook_size: 512
codebook_dim: 6
num_quantizers: 3
learning_rate: 1e-3
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.0e-3
scheduler:
  _target_: heptokens.models.utils.warmup_cosine_scheduler
  _partial_: true
  warmup_epochs: 5
  min_lr: 1.0e-6
