---
_target_: qhep.models.vq_vae.LitVqVae
encoder:
  _target_: qhep.models.coders.Encoder
  _partial_: true
  model:
    _target_: qhep.models.transformer.SetToVectorTransformer
    _partial_: true
    d_model: 128
    n_heads: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.
    activation: gelu
decoder:
  _target_: qhep.models.coders.Decoder
  _partial_: true
  model:
    _target_: qhep.models.transformer.VectorToSetTransformer
    _partial_: true
    max_set_size: ${datamodule.num_csts}
    d_model: 128
    n_heads: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.
    activation: gelu
codebook_size: 512
codebook_dim: 12
num_quantizers: 5
learning_rate: 1e-3
