---
# configs/model/transformer_vqvae.yaml
_target_: heptokens.models.vq_vae.LitVqVae
encoder:
  _target_: heptokens.models.coders.Encoder
  _partial_: true
  model:
    _target_: heptokens.models.transformer.Transformer
    _partial_: true
    d_model: 128
    n_heads: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.
    activation: gelu
decoder:
  _target_: heptokens.models.coders.Decoder
  _partial_: true
  model:
    _target_: heptokens.models.transformer.Transformer
    _partial_: true
    d_model: 128
    n_heads: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.
    activation: gelu
codebook_size: 512
codebook_dim: 6
num_quantizers: 3
learning_rate: 1e-3
