---
model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: 2
lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step
activation_monitor:
  _target_: heptokens.callbacks.monitor.ActivationMonitor
  logging_interval: 200
  layer_regex:
    - .*\.sa.fn$
    - .*\.ca.fn$
    - .*\.ff.fn$
    - .*\.gate$
    - .*encoder.layers\.\d+$
    - .*decoder.layers\.\d+$
  param_regex: [.*\.gate$]
checkpoint_per_epoch:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${full_path}/checkpoints
  filename: last
  enable_version_counter: false
  auto_insert_metric_name: false
checkpoint_best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${full_path}/checkpoints
  filename: best
  monitor: val/total_loss
  mode: min
  save_top_k: 1
  enable_version_counter: false
  auto_insert_metric_name: false
early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/total_loss
  patience: 10
  mode: min
reconstruction_monitor:
  _target_: heptokens.callbacks.recon.ReconstructionMonitor
  cst_fn:
    _target_: joblib.load
    filename: ${datamodule.transforms.preprocess.cst_fn.filename}
  jet_fn:
    _target_: joblib.load
    filename: ${datamodule.transforms.preprocess.jet_fn.filename}
  log_every_n_epochs: 1
  iqr_med_pt_min: 5000.0
  iqr_med_pt_max: 80000.0
  iqr_med_n_bins: 15
  iqr_med_min_entries_per_bin: 10
