---
# @package _global_
# Order indicates overwriting
defaults:
  - _self_
  - hydra: default
  - callbacks: pretrain
  - datamodule: atlas_mappable
  - model: classifier
  - experiment:
seed: 42  # For reproducibility
project_name: test_project  # Determines output directory path and wandb project
network_name: test  # Used for both saving and wandb
output_dir: /sdf/group/mli/samklein/code/gold_diggers/results  # TODO: put in shared space?
ckpt_path:  # Checkpoint path to resume training
weight_ckpt_path:  # Checkpoint path to load weights (but not optimizers etc)
save_test_preds: false  # After training, save test predictions to disk

# Extra tweaks available with the new pytorch version
precision: medium  # Should use medium if on ampere gpus
compile:  # Can set to default for faster compiles
tags:  # Extra tags passed to the logger

# COMPLETELY replaces the all config info with what is contained in ${full_path}
# This is ideal for resuming a job, log to the same directory
# Will also resume the logger and set the ckpt_path to the latest
full_resume: false
ckpt_flag: last.ckpt  # Name of the checkpoint file, can use wildcards
# Trainer settings
trainer:
  _target_: lightning.Trainer
  precision: bf16-mixed
  max_epochs: 1
  enable_progress_bar: true
  check_val_every_n_epoch:
  accelerator: auto
  devices: 1
  num_nodes: 1
  default_root_dir: ${full_path}
  # Below are useful for pretraining!
  reload_dataloaders_every_n_epochs: 1  # Allows the streaming dataloader to resume mid-epoch
  val_check_interval: 5_000
  limit_val_batches: 500  # Often don't need to run full val for pretraining
# Logger settings
logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  offline: false
  id:
  log_model: false
  tags: ${tags}
  project: ${project_name}
  name: ${network_name}
  save_dir: ${full_path}
  resume: ${full_resume}
# Interpolated paths
root_dir: .
full_path: ${output_dir}/${project_name}/${network_name}/
